# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Use Node.js
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run update-readme
    - run: |
        git config user.name gonzac-cod
        git config user.email gonzac.top@gmail.com
        git add README.md
        git commit -m "[bot] Update README with latest info"
        git push origin master
